# Numpy


In [2]:
import numpy as np
#method 1 
a = np.array([1,2,3,4,5])
print(a)

#method 2
print(np.arange(10))
print(np.arange(1,10))

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [3]:
# to know the version of numpy
print(np.__version__)

1.15.0


# why is it useful :- 

Memory efficient container that provide fast numerical operations

In [4]:
#python lists

L = range(10000)
%timeit [i**2 for i in L]

6.1 ms ± 250 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
a = np.arange(10000)
%timeit a**2

12.6 µs ± 178 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Creating Arrays

In [6]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
# converting list to ndarray
l = [1,2,3,4,5]
print(type(l))

t = (1,2,3,4,5)
print(type(t))

# asarray() is used to convert numpy array
l1 = np.asarray(l)
print(type(l1))
print(l1.dtype)

t1 = np.asarray(t , dtype = float)
print(type(t1))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
int32
<class 'numpy.ndarray'>


In [3]:
a = np.array([1,'mani',2,'raj'])
print(a)

['1' 'mani' '2' 'raj']


# numpy.fromiter

Create a new 1-dimensional array from an iterable object.


Properties of Iterator:

Iteration object remembers iteration count via internal count variable.

Once the iteration is complete, it raises a StopIteration exception and iteration count cannot be
reassigned to 0.

Therefore, it can be used to traverse the container just once.


In [20]:
# obtain iterator object from list 
import numpy as np 
list = range(5) 
it = iter(list)  # iter() method is used to convert an iterable to iterator.
                 #This presents another way to iterate the container i.e access its elements. 
                 #iter() uses next() for accessing values.
print(type(list))
print(type(it))        
print(it)

# for i in range(0,5):
#     print(next(it))


# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
print(x)
print(type(x))


<class 'range'>
<class 'range_iterator'>
[0. 1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [7]:
#print dimensions of an array
a.ndim           #ndim = n-dimensions

1

In [8]:
#know the shape of an array using shape attribute
a.shape

(5,)

In [9]:
#know the length of an array
len(a)

5

In [10]:
# 2-d array
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
print('dimensions : ',a.ndim)
print('shape : ',a.shape)  #(rows,columns)
print('length : ',len(a))  #returns the size of first dimension (rows,columns) but it returns only rows

dimensions :  2
shape :  (2, 3)
length :  2


In [12]:
#3-d array using lists
import pprint 
  
def ThreeD(a, b, c): 
    lst = [[ ['#' for col in range(a)] for col in range(b)] for row in range(c)] 
    return lst 
      
# Driver Code 
col1 = 5
col2 = 3
row = 2
# used the pretty printed function 
pprint.pprint(ThreeD(col1, col2, row)) 

[[['#', '#', '#', '#', '#'],
  ['#', '#', '#', '#', '#'],
  ['#', '#', '#', '#', '#']],
 [['#', '#', '#', '#', '#'],
  ['#', '#', '#', '#', '#'],
  ['#', '#', '#', '#', '#']]]


In [13]:
#3-d array using numpy
b = np.array([  [  [1,2],[3,4],[5,6]  ] , [  [7,8],[9,10],[11,12]  ]  ])
b

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [14]:
print(b.ndim)
print(b.shape)
print(len(b))

3
(2, 3, 2)
2


In [15]:
c = np.array([  [  [ [1,2],[3,4],[5,6] ] , [ [7,8],[9,10],[11,12] ]  ]  ])
c

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]]])

In [16]:
print(c.ndim)
print(c.shape)
print(len(c))

4
(1, 2, 3, 2)
1


# functions for creating arrays

In [17]:
# arange function
# arange function is an array-valued function of a built-in python range function

In [18]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a = np.arange(1,20,2)    #(start,end(exclusive),stepsize)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
a = np.linspace(1,2,5)   #(start,end(exclusive),number of points)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
a = np.logspace(1.0, 2.0, num = 10)    #This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale.
                                       #default base is 10
print("Base 10 : ",a)


print()
print()
# set base of log space to 2 

a = np.logspace(1,10,num = 10, base = 2) 
print('Base 2 : ',a)

Base 10 :  [ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


Base 2 :  [   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [21]:
# common arrays

a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.eye(3)  #returns a 2-d array with ones on the diagonals and zeros elsewhere

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [131]:
np.eye(3,4)  #3 is number of rows, 4 is number of colums

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [25]:
# creating array using diag function
a = np.diag([1,2,3,4])  # creates a diagonal array

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
np.diag(a)  # extracts diagonal

array([1, 2, 3, 4])

In [27]:
#create array using random

#create a array of given shape and populate it with ramdom samples

# this generates a uniform distributed number
a = np.random.rand(4)
a

array([0.45539363, 0.4542628 , 0.13342402, 0.75641801])

In [28]:
a = np.random.randn(4)  #returns a sample from the 'guassian distributed/standard normal variate'
a

array([-0.11669459, -0.10737892, -0.77642479, -0.60484596])

# Basic datatypes

In [29]:
a = np.arange(10)
print(a)
a.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int32')

In [30]:
#you can explicitly provide which datatype you want

In [31]:
a = np.arange(10, dtype='float64')
print(a)
print(a.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [32]:
#complex arrays

b = np.array([1+2j,2+4j])
print(b)
print(b.dtype)

[1.+2.j 2.+4.j]
complex128


In [33]:
b = np.array([True,False,True,False])
print(b)
print(b.dtype)

[ True False  True False]
bool


In [34]:
s = np.array(['mani','raj','langaru'])
s

array(['mani', 'raj', 'langaru'], dtype='<U7')

In [35]:
s.dtype

dtype('<U7')

# each built-in data type has a character code that uniquely identifies it

'b'      -  boolean

'i'      -  (signed)integer

'u'      -  (unsigned)integer

'f'      -  floating point

'c'      -  complex floating point

'm'      -  timedelta

'M'      -  datetime

'O'      -  Python objects

'S','a'  -  (bite)string

'U'      -  unicode

'V'      -  raw data (void)


# Indexing and Slicing

In [36]:
a = np.arange(10)
print(a[5])
print(a[5:])

5
[5 6 7 8 9]


In [37]:
# for multi-dimensional arrays , indexes are tuple of integers:
a = np.diag([1,2,3])
print(a)
print(a[2,2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [38]:
a[2,2] = 5
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 5]]


# slicing

In [39]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a[1:8:2]

array([1, 3, 5, 7])

In [41]:
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [42]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [43]:
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# How to create a boolean array?

Create a 3×3 numpy array of all True’s

In [44]:
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Extract all odd numbers from arr

In [45]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[1::2]
#or
arr[arr % 2 == 1]


array([1, 3, 5, 7, 9])

 Replace all odd numbers in arr with -1

In [46]:
arr[1::2] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Q). How to replace items that satisfy a condition without affecting the original array?

Replace all odd numbers in arr with -1 without changing arr

In [47]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [48]:
out = np.where(arr % 2 == 1)
print(out)

(array([1, 3, 5, 7, 9], dtype=int64),)


Q)Convert a 1D array to a 2D array with 2 rows

In [49]:
a = np.arange(10)
a.reshape(2,-1)    ## Setting to -1 automatically decides the number of cols


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,5)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [51]:
#method 1
np.concatenate([a,b],axis = 0)  # axis = 0 for stacking verticall and 1 for stacking horizontally

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [52]:
#method 2 
print(np.vstack([a,b]) )  #vstack = vericallyStack
print(np.hstack([a,b]))   #hstack = horizontalStack

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [53]:
#method 3 
print(np.r_[a,b])  #verticalStack
print(np.c_[a,b])  #horizontalStack

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [54]:
#repeat function
a = np.arange(3)
print(a)
print(np.r_[np.repeat(a,3)])

[0 1 2]
[0 0 0 1 1 1 2 2 2]


In [55]:
#tile function
print(np.r_[np.tile(a,3)])

[0 1 2 0 1 2 0 1 2]


#  Get the common items between a and b

In [62]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a,b))


[2 4]


#  How to remove from one array those items that exist in another?

From array a remove all items present in array b

Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

Desired Output:

array([1,2,3,4])

In [65]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
print(np.setdiff1d(a,b))

[1 2 3 4]


# How to get the positions where elements of two arrays match?

Get the positions where elements of a and b match

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:

#> (array([1, 3, 5, 7]),)

In [69]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.where(a==b))  # it only returns the index values of the same values
print(a[np.where(a==b)]) # it returns the same element values



(array([1, 3, 5, 7], dtype=int64),)
[2 2 4 4]


#  How to extract all numbers between a given range from a numpy array?

Get all items between 5 and 10 from a.

Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])

Desired Output:

(array([6, 9, 10]),)

In [75]:
a = np.array([2,6,1,9,10,3,27])

#method 1
index = np.where((a>5) & (a<10))
print('method 1 : ',a[index])

#method 2 
index = np.where(np.logical_and(a>5,a<10))
print('method 2 : ',a[index])

#method 3
print('method 3 : ',a[(a>5) & (a<10)])

method 1 :  [6 9]
method 2 :  [6 9]
method 3 :  [6 9]


# How to swap two columns in a 2d numpy array?

Swap columns 1 and 2 in the array arr.

In [76]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
#solution
#syntax arr[rows:columns]

arr[:, [1,0,2]]   #arr[:,[column1,column0,column2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Swap rows 1 and 2 in the array arr.

In [84]:
#solution
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

Reverse the rows of a 2D array arr

In [85]:
#solution
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

Reverse the columns of a 2D array arr.

In [86]:
arr[: , ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [91]:
# solution method 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
rand_arr

array([[5.32430924, 7.87885968, 9.19770391],
       [5.42299098, 7.78179784, 8.96520492],
       [7.90086238, 8.22930108, 6.61356571],
       [8.43778297, 9.79061124, 9.38191315],
       [6.9819028 , 8.5673538 , 8.84672973]])

In [90]:
# Solution Method 2:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[9.44600262 8.10626213 5.47306672]
 [9.56464806 9.62884468 8.13883084]
 [5.92712923 9.51136141 8.9981691 ]
 [6.81386448 5.74570041 7.082144  ]
 [7.25780159 6.79782553 5.25268995]]


# How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

Input:

# Create the random array

np.random.seed(100)

rand_arr = np.random.random([3,3])/1e3

rand_arr

#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])

Desired Output:

#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])


In [92]:
#np.random.seed() is used to get same random number again and again to use it in different scenerios

In [116]:
# solution

# Reset printoptions to default
np.set_printoptions(suppress=False)    #These options determine the way floating point numbers, arrays and other NumPy objects are displayed.

# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434049e-04, 2.783694e-04, 4.245176e-04],
       [8.447761e-04, 4.718856e-06, 1.215691e-04],
       [6.707491e-04, 8.258528e-04, 1.367066e-04]])

In [110]:
np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

# Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

Input:

a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Desired Output:

#> array([ 0,  1,  2, ..., 12, 13, 14])

In [130]:
np.set_printoptions(threshold=6)   # threshold value only 6 is possible

a = np.arange(10)
print(a)

# Print the full numpy array a without truncating.

np.set_printoptions(threshold=np.nan)
print(a)

[0 1 2 ... 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [10]:
a = np.array([1,2,3,4])
print(a+1)    # it doesn't affect to original array
print(a**2)   # it doesn't affect to original array
print(a)      # original value is not affected

[2 3 4 5]
[ 1  4  9 16]
[1 2 3 4]


# File operations

In [77]:
# load file using numpy

# data = np.loadtxt("path")

# Element wise Arithmatic Operations

In [11]:
b = np.ones(4)+1
print(b)
print(a)
print()
print()
print(a - b)

[2. 2. 2. 2.]
[1 2 3 4]


[-1.  0.  1.  2.]


In [12]:
print(a*b)

[2. 4. 6. 8.]


In [13]:
print(a/b)

[0.5 1.  1.5 2. ]


In [18]:
print(a%b)

[1. 0. 1. 0.]


In [20]:
a = np.array([1,2,3,4,5])
b = np.array([5,2,1,6,4])

print(a==b)  # it does index wise comparision and return true if matched else false
print()
print(a>b)   # it does index wise comparision and return true if matched else false

[False  True False False False]

[False False  True False  True]


In [23]:
# array wise comparision

a = np.array([1,2,3,4,5])
b = np.array([5,2,6,4,8])
c = np.array([1,2,3,4,5])

print(np.array_equal(a,b))   # it returns true if the whole array is matched else false
print()
print(np.array_equal(a,c))

False

True


In [32]:
# Matrix Manipulation

c = np.diag([1,2,3,4])
print(c)
print()
print(c * c)
print()
print(c + c)



[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]

[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]


# Logical Operations

In [30]:
a = np.array([1,1,0,0])
b = np.array([1,0,1,0])

#and operation
print(np.logical_and(a,b))
print()

#or operation
print(np.logical_or(a,b))
print()

#xor operation
print(np.logical_xor(a,b))
print()


[ True False False False]

[ True  True  True False]

[False  True  True False]



# Transcendental functions

In [33]:
a = np.array([1,2,3,4,5])

print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [34]:
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [35]:
print(a)

[1 2 3 4 5]


In [37]:
print(np.exp(a))   #evaluates e^x for each element in a given input

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


# shape mismatch

In [39]:
a = np.arange(5)

a + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

# Basic Reductions

In [42]:
x = np.array([1,2,3,4,5])
y = np.arange(1,5)
print(x)
print(y)
print(type(x))
print(type(y))

print(np.sum(x))
print(np.sum(y))

[1 2 3 4 5]
[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
15
10


computing sums

In [43]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [44]:
#axis = 0 adds elements column wise
x.sum(axis=0)   #[1+2,1+2]    

array([3, 3])

In [45]:
#axis = 1 adds elements row wise
x.sum(axis=1)    

array([2, 4])

In [46]:
x.min()

1

In [47]:
x.max()

2

In [48]:
x.argmin()  # index of minimum element
x.argmax()  # index of maximum element

0

 # logical operations

In [54]:
print(np.all([True,True,True,True]))   # returns true if all the elements are true
print(np.all([True,True,True,False]))

True
False


In [56]:
print(np.any([True,True,False,True]))  # returns True is any of the element is True
print(np.any([False,False,False,True]))

True
True


In [58]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
np.any(a != 0)


False

In [60]:
np.all(a == 0)

True

In [61]:
np.all(a == a)

True

In [64]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,8,4,2])
c = np.array([6,8,3,4,9])
print(((a<b) & (b>c)).all())
print(((a<b) & (b>c)).any())


False
True


# statistics

In [66]:
x = np.array([1,2,3,4,5])
y = np.array([[1,5,3,6],[5,3,7,8]])

print(x.mean())
print(np.median(x))

3.0
3.0


In [75]:
print(y.mean())
print(np.median(y))
print(np.median(y,axis = -1))  # last axis
print(np.median(y,axis = 0))   #axis = 0 (columns)
print(np.median(y,axis = 1))   #axis = 1 (rows)

4.75
5.0
[4. 6.]
[3. 4. 5. 7.]
[4. 6.]


# array Broadcasting

In [8]:
a = np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [12]:
a = np.tile(np.arange(0,40,10),(3,1))
print(a)
print('dimesion : ',a.ndim)

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [22]:
a = np.tile(np.arange(0,40,10),(3,2))
print(a)
print('dimesion : ',a.ndim)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]
dimesion :  2


In [16]:
a = np.tile(np.arange(0,40,10),(4,3))
print(a)
print('dimesion : ',a.ndim)

array([[ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30]])

In [4]:
a = np.tile(np.arange(0,40,10),(3,1))
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [5]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [6]:
a+b  #throws error 

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [20]:
c = a.T
print(c)
print(c.ndim)

[ 0 10 20 30]
1


In [11]:
c + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [32]:
a = np.arange(0,40,10)
print(a.shape)
print(a.ndim)


(4,)
1


In [33]:
print(a)
print('dimesion : ',a.ndim)
print()

a = a[:,np.newaxis]   # adds a new axis to existing dimensional array(ie., it converts 2d array to 3d array and so on)
print(a)
print(a.shape)
print('dimesion : ',a.ndim)

[ 0 10 20 30]
dimesion :  1

[[ 0]
 [10]
 [20]
 [30]]
(4, 1)
dimesion :  2


# Flattening

In [30]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a.ravel()     # it returns a continuous flattening array


array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
a.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [32]:
 a.T.ravel()

array([1, 5, 2, 6, 3, 7, 4, 8])

# Reshapping

The inverse operation to Flattening

In [33]:
print(a)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [35]:
b = a.ravel()
print(b)
print(b.shape)

[1 2 3 4 5 6 7 8]
(8,)


In [40]:
x = b.reshape(2*4)
print(x)

[1 2 3 4 5 6 7 8]


In [41]:
b = b.reshape(2,4)
print(b)


[[1 2 3 4]
 [5 6 7 8]]


In [42]:
b[0,0] = 100
b[1,1] = 200
print(b)

[[100   2   3   4]
 [  5 200   7   8]]


In [43]:
a = np.zeros((3,2))
b = a.T.reshape(3*2)
print(b)
b[1] = 50
print(b)
print(a)

[0. 0. 0. 0. 0. 0.]
[ 0. 50.  0.  0.  0.  0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


# dimension shuffling

In [48]:
a = np.arange(4*3*2)
print(a)
print(a.ndim)
print()
a = np.arange(4*3*2).reshape(4,3,2)   #reshape(matrices,rows,columns)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
3


In [51]:
a[0,2,1]    #a[index,row,column]

5

# Resizing

In [62]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

However it must not be referred to some other variables

In [61]:
b = a
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

# sorting data

In [65]:
a = np.array([[1,8,5],[5,3,4]])
b = np.sort(a,axis = 1)
print(b)
print()
c = np.sort(a,axis = 0)
print(c)

[[1 5 8]
 [3 4 5]]

[[1 3 4]
 [5 8 5]]


In [67]:
a.sort(axis = 0)
print(a)    # original array is affected

[[1 3 4]
 [5 8 5]]


In [68]:
a.sort(axis = 1)
print(a)   

[[1 3 4]
 [5 5 8]]


In [70]:
#sorting with fancy indexing
a = np.array([4,3,1,2])      
j = np.argsort(a)        #index of the numbers are returned according to their position.suppose 1 is at index 2 , 2 is at index 3, 3 is at index 1 and 4 is at index 0
print(j)

[2 3 1 0]


In [71]:
a[j]

array([1, 2, 3, 4])